### ISSUE TITLE
Wrong public profile URL in webfinger in sub-directory install

### ISSUE THREAD

**Issue by loxK** [nextcloud/social#721]
**Describe the bug**
There is an issue with the public profile url returned by webfinger in sub-directory installation of Nextcloud. The sub-directory is added twice to the url.

**To Reproduce**
1. Install Nextcloud in a subdirectory
2. Go to 'https://mycloud.io/.well-known/webfinger?resource=acct:user@mycloud.io'
4. See error the profile url: 
`{"subject":"acct:user@mydomain.io","links":[{"rel":"self","type":"application\/activity+json","href":"https:\/\/mydomain.io\/nextcloud\/nextcloud\/apps\/social\/@user"},{"rel":"http:\/\/ostatus.org\/schema\/1.0\/subscribe","template":"https:\/\/mydomain.io\/nextcloud\/apps\/social\/ostatus\/follow\/{uri}"}]}`

**Expected behavior**
The profile url should be correct, but it has the subdirectory twice: https://mydomain.io/nextcloud/nextcloud/apps/social/@user

**Client details:**
 - OS: Ubuntu
 - Browser Firefox
 - Version 68.0.2
 - Device: desktop

<details>
<summary>Server details</summary>

**Social app version:**  0.2.101

**Operating system:** Linux 4.15.0-60-generic #67~16.04.1-Ubuntu SMP Mon Aug 26 08:57:33 UTC 2019 x86_64

**Webserver:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** mysql 10.0.38

**PHP version:** 

7.3.8-1+ubuntu16.04.1+deb.sury.org+1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, ldap, exif, msgpack, mysqli, pdo_mysql, pdo_sqlite, Phar, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, memcached, libsmbclient, Zend OPcache

**Nextcloud version:** 16.0.4 - 16.0.4.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

</details>

**Comment by StCyr** [comment]
I think I got this problem and @daita fixed it easily.

IIRC, you should have a look at the `social_url`setting (and fix it if it's wrong):

`sudo -u www-data php occ config:app:get social social_url`

IIRC, @daita told me this problem was due to a bug in the version I'd originaly installed, and that's it's fixed in master for long now.

**Comment by loxK** [comment]
This command returns me an wrong result. I fixed it with:

`occ config:app:set social social_url --value "https://mydomain.io/nextcloud/apps/social/"`

Weird enough nor `occ social:reset` and `occ social:reset --uninstall` fixed it.
Even worst if I do `occ social:reset` the data seems to be reset, but it doesn't fix anything. I then did `occ social:reset --uninstall` and then reinstalled the app: after loadind the social app my personal user data is back. (followed, posts etc.)

**Comment by StCyr** [comment]
Could you also verify the other social settings (address, cloud_url, social_address)?

`sudo -u www-data php occ config:app:get social address`
`sudo -u www-data php occ config:app:get social cloud_url`
`sudo -u www-data php occ config:app:get social social_address`

**Comment by daita** [comment]
@loxK reset only emptied the tables, uninstall remove them and reinstalling the app recreated your tables; and fixed your issue !

**Comment by loxK** [comment]
No, reset (multiple by the way and two with --uninstall) did not fix my issue.

Only `occ config:app:set social social_url --value "https://mydomain.io/nextcloud/apps/social/"` did it.

After using reset, data get emptied but profile url was still wrong, doing reset --uninstall got the data back after reinstalling the app. And I could reproduce that latest behavior twice.

**Comment by loxK** [comment]
BTW only cloud_url and social_url are set:

```
root@nextcloud ~ » occ config:app:get social address
root@nextcloud ~ » occ config:app:get social cloud_url
https://mydomain.io/nextcloud
root@nextcloud ~ » occ config:app:get social social_address
root@nextcloud ~ » occ config:app:get social social_url
https://mydomain.io/nextcloud/apps/social/
```

**Comment by daita** [comment]
and during the `social:reset`, when asked to specify an address, which one did you used ?

**Comment by loxK** [comment]
I used https://mydomain.io/nextcloud
